spring:
  profiles:
    active: local
  application:
    name: sample-company-api
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/mydatabase?user=myuser&password=secret
      schema: sample_company
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: sample_company
    open-in-view: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: sample_company

  security:
    user:
      name: "test"
      password: "{bcrypt}$2a$08$TIvt7DUNlNXrWB6fR6Jfj.0APMa9R5QfIi1KmWDvRbkYE50qQ6Mja"

springdoc:
  swagger-ui:
    tagsSorter: alpha
  api-docs:
    groups:
      enabled: true

server:
  port: 8091
  servlet:
    context-path: /
  compression:
    enabled: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info
      base-path: /.well-known
      path-mapping:
        info: ready
        health: live
  endpoint:
    info:
      enabled: true
    health:
      enabled: true

logging:
  level:
    org.hibernate:
      SQL: DEBUG

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase?user=myuser&password=secret
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: true
